version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: whisperchat_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: whisperchat
    volumes:
      - whisperchat_data:/var/lib/postgresql/data

volumes:
  whisperchat_data:
