version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: whisperchat_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: whisperchat
    volumes:
      - whisperchat_data:/var/lib/postgresql/data
  
  minio:
    image: minio/minio
    container_name: whisperchat_minio
    command: server/data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9006:9006"  # S3 API
      - "9001:9001"  # MinIO Console
    volumes:
      - minio_data:/data

volumes:
  whisperchat_data:
  minio_data:
